package parser

import (
	"fmt"
	"strings"
)

func GenerateGoFile(tables []Table, enumSet map[string]bool, packageName string) string {
	var sb strings.Builder
	sb.WriteString("// Code generated by fbs-parser; DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	// Start our top-level map
	sb.WriteString("var Tables = map[string][]map[string]string{\n")

	for _, tbl := range tables {
		sb.WriteString(fmt.Sprintf("  %q: {\n", tbl.Name))

		for _, f := range tbl.Fields {
			// Join metadata with comma delimiter (or any other you prefer)
			metaJoined := strings.Join(f.Meta, ",")

			// Map FBS type to Go type
			goType := fbTypeToGoType(f.Type, enumSet)

			// Build the map literal
			sb.WriteString("    {\n")
			sb.WriteString(fmt.Sprintf("      \"name\": %q,\n", f.Name))
			// sb.WriteString(fmt.Sprintf("      \"fbtype\": %q,\n", f.Type))
			sb.WriteString(fmt.Sprintf("      \"type\": %q,\n", goType))
			sb.WriteString(fmt.Sprintf("      \"defaultValue\": %q,\n", f.DefaultValue))
			sb.WriteString(fmt.Sprintf("      \"meta\": %q,\n", metaJoined))
			sb.WriteString("    },\n")
		}
		sb.WriteString("  },\n")
	}

	sb.WriteString("}\n")

	// Generate Initializer functions in below format
	// func Init{TableName}(v *{TableName}) *{TableName} {
	// 	if v == nil {
	// 		v = &{TableName}{}
	// 	}
	// 	return v
	// }

	return sb.String()
}
