// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package books

import "strconv"

type AdType byte

const (
	AdTypeUNKNOWN              AdType = 0
	AdTypeDISPLAY              AdType = 1
	AdTypeVIDEO                AdType = 2
	AdTypePRODUCT              AdType = 3
	AdTypeDISPLAY_WITH_PRODUCT AdType = 4
	AdTypeVIDEO_WITH_PRODUCT   AdType = 5
)

var EnumNamesAdType = map[AdType]string{
	AdTypeUNKNOWN:              "UNKNOWN",
	AdTypeDISPLAY:              "DISPLAY",
	AdTypeVIDEO:                "VIDEO",
	AdTypePRODUCT:              "PRODUCT",
	AdTypeDISPLAY_WITH_PRODUCT: "DISPLAY_WITH_PRODUCT",
	AdTypeVIDEO_WITH_PRODUCT:   "VIDEO_WITH_PRODUCT",
}

var EnumValuesAdType = map[string]AdType{
	"UNKNOWN":              AdTypeUNKNOWN,
	"DISPLAY":              AdTypeDISPLAY,
	"VIDEO":                AdTypeVIDEO,
	"PRODUCT":              AdTypePRODUCT,
	"DISPLAY_WITH_PRODUCT": AdTypeDISPLAY_WITH_PRODUCT,
	"VIDEO_WITH_PRODUCT":   AdTypeVIDEO_WITH_PRODUCT,
}

func (v AdType) String() string {
	if s, ok := EnumNamesAdType[v]; ok {
		return s
	}
	return "AdType(" + strconv.FormatInt(int64(v), 10) + ")"
}
