// Code generated by fbs-parser; DO NOT EDIT.
package books

var Tables = map[string][]map[string]string{
  "Creative": {
    {
      "name": "Id",
      "type": "uint64",
      "defaultValue": "",
      "meta": "",
    },
    {
      "name": "Name",
      "type": "string",
      "defaultValue": "",
      "meta": "",
    },
    {
      "name": "CampaignId",
      "type": "uint64",
      "defaultValue": "",
      "meta": "",
    },
    {
      "name": "Rate",
      "type": "float64",
      "defaultValue": "",
      "meta": "",
    },
    {
      "name": "ListField",
      "type": "[]string",
      "defaultValue": "",
      "meta": "",
    },
    {
      "name": "ScalarListField",
      "type": "[]uint64",
      "defaultValue": "",
      "meta": "",
    },
  },
  "CreativeList": {
    {
      "name": "Children",
      "type": "[]Creative",
      "defaultValue": "",
      "meta": "",
    },
  },
  "Book": {
    {
      "name": "Id",
      "type": "uint64",
      "defaultValue": "",
      "meta": "",
    },
    {
      "name": "Title",
      "type": "string",
      "defaultValue": "",
      "meta": "",
    },
    {
      "name": "PageCount",
      "type": "uint64",
      "defaultValue": "",
      "meta": "",
    },
    {
      "name": "Rate",
      "type": "float64",
      "defaultValue": "",
      "meta": "",
    },
    {
      "name": "ListField",
      "type": "[]string",
      "defaultValue": "",
      "meta": "",
    },
    {
      "name": "ScalarListField",
      "type": "[]uint64",
      "defaultValue": "",
      "meta": "",
    },
  },
  "BookList": {
    {
      "name": "Children",
      "type": "[]Book",
      "defaultValue": "",
      "meta": "",
    },
  },
}
